A pipeline will run my experiment on a specialized Kubernetes pod on each push

diff --git a/.github/workflows/mlops.yaml b/.github/workflows/mlops.yaml
--- a/.github/workflows/mlops.yaml
+++ b/.github/workflows/mlops.yaml
@@ -1,61 +1,85 @@
 name: MLOps
 
 on:
+  # Runs on pushes targeting main branch
   push:
     branches:
       - main
+
+  # Runs on pull requests
   pull_request:
+
+  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
 
+# Allow the creation and usage of self-hosted runners
 permissions:
   contents: read
   id-token: write
 
 jobs:
-  train-and-report:
-    permissions: write-all
-    runs-on: self-hosted
+  setup-runner:
+    runs-on: [self-hosted, base-runner]
     if: github.event_name == 'pull_request'
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
-
+      - name: Login to Google Cloud
+        uses: google-github-actions/auth@v2 with:
+          credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
+      - name: Get Google Cloud's Kubernetes credentials
+        uses: google-github-actions/get-gke-credentials@v2 with:
+          cluster_name: ${{ secrets.GCP_K8S _CLUSTER_NAME }} location: ${{
+          secrets.GCP_K8S_CLUSTER _ZONE }}
+      - name: Set up GCloud SDK
+        uses: google-github-actions/setup-gcloud@v2 with:
+          version: '>= 494.0.0'
+      - name: Install kubectl
+        run: |
+          gcloud components install kubectl
+      - name: Install gke-gcloud-auth-plugin
+        run: |
+          gcloud components install gke-gcloud-auth-plugin
+      - name: Initialize runner on Kubernetes
+        env:
+          KUBECONFIG_DATA: ${{ secrets.GCP_K8S_KUBECONFIG }}
+        # We use envsubst to replace variables in runner-gpu.yaml
+        # in order to create a unique runner name with the
+        # GitHub run ID. This prevents conflicts when multiple
+        # runners are created at the same time.
+        run: |
+          echo "$KUBECONFIG_DATA" > kubeconfig export KUBECONFIG=kubeconfig
+          # We use run_id to make the runner name unique
+          export GITHUB_RUN_ID="${{ github.run_id }}" envsubst <
+          kubernetes/runner-gpu.yaml | kubectl apply -f -
+  train-and-report:
+    permissions: write-all
+    needs: setup-runner
+    runs-on: [self-hosted, gpu-runner]
+    if: github.event_name == 'pull_request' steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
       - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: '3.11'
-          cache: pip
-
+        uses: actions/setup-python@v5 with:
+          python-version: '3.11' cache: pip
       - name: Install dependencies
         run: pip install --requirement requirements-freeze.txt
-
       - name: Login to Google Cloud
-        uses: google-github-actions/auth@v2
-        with:
+        uses: google-github-actions/auth@v2 with:
           credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
-
       - name: Train model
         run: dvc repro --pull
-
       - name: Push the outcomes to DVC remote storage
         run: dvc push
-
       - name: Commit changes in dvc.lock
-        uses: stefanzweifel/git-auto-commit-action@v5
-        with:
-          commit_message: "Commit changes in dvc.lock"
-          file_pattern: dvc.lock
-
+        uses: stefanzweifel/git-auto-commit-action@v5 with:
+          commit_message: Commit changes in dvc.lock file_pattern: dvc.lock
       - name: Setup Node
-        uses: actions/setup-node@v4
-        with:
+        uses: actions/setup-node@v4 with:
           node-version: 20
-
       - name: Setup CML
-        uses: iterative/setup-cml@v2
-        with:
+        uses: iterative/setup-cml@v2 with:
           version: '0.20.0'
-
       - name: Create CML report
         env:
           REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -67,43 +91,42 @@ jobs:
           echo "# Experiment Report (${{ github.sha }})" >> report.md
 
           # Compare parameters to main branch
-          echo "## Params workflow vs. main" >> report.md
-          dvc params diff main --md >> report.md
+          echo "## Params workflow vs. main" >> report.md dvc params diff main --md >>
+          report.md
 
           # Compare metrics to main branch
-          echo "## Metrics workflow vs. main" >> report.md
-          dvc metrics diff main --md >> report.md
+          echo "## Metrics workflow vs. main" >> report.md dvc metrics diff main --md >>
+          report.md
 
           # Compare plots (images) to main branch
           dvc plots diff main
 
-          # Create plots in the report
+          # Create plots
           echo "## Plots" >> report.md
 
-          # Training history plot
-          echo "### Training History" >> report.md
-          echo "#### main" >> report.md
-          echo '![](./dvc_plots/static/main_evaluation_plots_training_history.png "Training History")' >> report.md
-          echo "#### workspace" >> report.md
-          echo '![](./dvc_plots/static/workspace_evaluation_plots_training_history.png "Training History")' >> report.md
+          # Create training history plot
+          echo "### Training History" >> report.md echo "#### main" >> report.md echo
+          '![](./dvc_plots/static/main_evaluation_plots_training_history.png "Training History")'
+          >> report.md echo "#### workspace" >> report.md echo
+          '![](./dvc_plots/static/workspace_evaluation_plots_training_history.png "Training History")'
+          >> report.md
 
-          # Predictions preview
-          echo "### Predictions Preview" >> report.md
-          echo "#### main" >> report.md
-          echo '![](./dvc_plots/static/main_evaluation_plots_pred_preview.png "Predictions Preview")' >> report.md
-          echo "#### workspace" >> report.md
-          echo '![](./dvc_plots/static/workspace_evaluation_plots_pred_preview.png "Predictions Preview")' >> report.md
+          # Create predictions preview
+          echo "### Predictions Preview" >> report.md echo "#### main" >> report.md echo
+          '![](./dvc_plots/static/main_evaluation_plots_pred_preview.png "Predictions Preview")'
+          >> report.md echo "#### workspace" >> report.md echo
+          '![](./dvc_plots/static/workspace_evaluation_plots_pred_preview.png "Predictions Preview")'
+          >> report.md
 
-          # Confusion matrix
-          echo "### Confusion Matrix" >> report.md
-          echo "#### main" >> report.md
-          echo '![](./dvc_plots/static/main_evaluation_plots_confusion_matrix.png "Confusion Matrix")' >> report.md
-          echo "#### workspace" >> report.md
-          echo '![](./dvc_plots/static/workspace_evaluation_plots_confusion_matrix.png "Confusion Matrix")' >> report.md
+          # Create confusion matrix
+          echo "### Confusion Matrix" >> report.md echo "#### main" >> report.md echo
+          '![](./dvc_plots/static/main_evaluation_plots_confusion_matrix.png "Confusion Matrix")'
+          >> report.md echo "#### workspace" >> report.md echo
+          '![](./dvc_plots/static/workspace_evaluation_plots_confusion_matrix.png "Confusion Matrix")'
+          >> report.md
 
           # Publish the CML report
           cml comment update --target=pr --publish report.md
-
   publish-and-deploy:
     runs-on: ubuntu-latest
     if: github.ref == 'refs/heads/main'
@@ -163,3 +186,27 @@ jobs:
           kubectl apply \
             -f kubernetes/deployment.yaml \
             -f kubernetes/service.yaml
+  cleanup-runner:
+    needs: train-and-report
+    runs-on: [self-hosted, base-runner]
+    # Run this job if the event is a pull request and regardless of whether the previous job failed or was cancelled
+    if: github.event_name == 'pull_request' && (success() || failure() || cancelled())
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+      - name: Set up GCloud SDK
+        uses: google-github-actions/setup-gcloud@v2 with:
+          version: '>= 494.0.0'
+      - name: Install kubectl
+        run: |
+          gcloud components install kubectl
+      - name: Install gke-gcloud-auth-plugin
+        run: |
+          gcloud components install gke-gcloud-auth-plugin
+      - name: Cleanup runner on Kubernetes
+        env:
+          KUBECONFIG_DATA: ${{ secrets.GCP_K8S_KUBECONFIG }}
+        run: |
+          echo
+          "$KUBECONFIG_DATA" > kubeconfig export KUBECONFIG=kubeconfig export GITHUB_RUN_ID="${{
+          github.run_id }}" envsubst < kubernetes/runner-gpu.yaml | kubectl delete --wait=false -f -
